// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"wire-demo/pkgBar"
	"wire-demo/pkgFoo"
)

// Injectors from wire.go:

func InitializeBigStructTypeInstance(phrase string) (*BigStructType, error) {
	message := NewMessage(phrase)
	greeter := NewGreeter(message)
	event, err := NewEvent(greeter)
	if err != nil {
		return nil, err
	}
	typeA := pkgFoo.NewTypeA()
	typeB := pkgFoo.NewTypeB()
	typeC := pkgBar.NewTypeC()
	typeD := pkgBar.NewTypeD()
	bigStructType := NewBigStructType(event, typeA, typeB, typeC, typeD)
	return bigStructType, nil
}
